### ISSUE TITLE
[Chore] 노래 제목 변경

### ISSUE THREAD

**Issue by jiyoungsophia** [DeveloperAcademy-POSTECH/2024-MC3-A7-Anigeunde#42]
## 🐼 About

* 우클릭 시 뜨는 곡명 변경 기능 추가할 예정입니다

## 🌲 Branch Name

Chore/#42-SideBarView-update

**Comment by OneMoreThink** [comment]
- 마일스톤 branch에 반영된 사항입니다. 
- 마일스톤 branch를 develop에 merge 하면서 함께 반영된 사항이라 이슈를 종료합니다.
