### ISSUE TITLE
[Hotfix] 애플 리젝사항 수정 

### ISSUE THREAD

**Issue by OneMoreThink** [DeveloperAcademy-POSTECH/2024-MC3-A7-Anigeunde#81]
## Reject 사유
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed your app encourages or directs users to allow the app to access the microphone. Specifically, your app directs the user to grant permission in the following way(s):
- A custom message appears before the permission request, and the user can close the message and delay the permission request with the Skip button. The user should always proceed to the permission request after the message.
Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.

### Next Steps
To resolve this issue, please revise the permission request process in your app to not include an exit button on the message before the permission request.

If necessary, you may provide more information about why you are requesting permission before the request appears. If the user is trying to use a feature in your app that won't function without access to the microphone, you may include a notification to inform the user and provide a link to the Settings app.

- 첨부파일 
 ![image](https://github.com/user-attachments/assets/8683091b-c39c-4b92-bb8c-f58ccf5864f1)

## 이해한 내용
- 마이크 선택을 통해 사용자로부터 마이크 사용 권한을 받는 프로세스상에서 skip 버튼이 제공되어 사용자가 마이크 권한을 명시적으로 주지 않는 Flow가 생기는게 문제인거 같습니다. 
- 또한 실제 마이크 사용 시작 지점에서 마이크의 권한이 없는 경우에 대한 대응 로직 또한 필요할 것 같습니다. 

## 해야할 일 
1. 마이크 선택 화면 수정
- [x] 'Skip' 버튼 제거

2. 플레이 버튼 로직 수정
- [x] 플레이 버튼 클릭 시 마이크 권한 체크 로직 추가
- [x]  마이크 권한이 없을 경우
a) 사용자에게 권한 필요성을 설명하는 알림(alert) 표시
b) 알림에 시스템 설정으로 이동하는 옵션 포함
c) 사용자가 설정에서 권한을 부여할 수 있도록 안내

## 🌲 Branch Name
Hotfix/#81-ReviseMicAuthorizationRequestFlow

**Comment by Kimajun0919** [comment]
권한 설정 허용 관련 온보딩이나 안내가 없어서 생기는 문제는 아닌가영?!?
